###### To solve a puzzle, you are given an initial state and a goal state.
###### Target is to reach goal state from initial state using puzzle rules.
######  We can move blank tile only on left, right, up, and down
![Capture.JPG](attachment:Capture.JPG)

# Generate an intial state of NPuzzle

In [1]:
import numpy as np
import random
def get_state(N):    
    state = [item for item in range(N*N)]# [0,1,2,...,15]
    random.shuffle(state)
    tmp = np.array(state)
    print(tmp.reshape(N,N))
    return state

In [2]:
get_state(3)

[[4 6 1]
 [3 0 5]
 [7 2 8]]


[4, 6, 1, 3, 0, 5, 7, 2, 8]

# Calculate inversion

Inversion is a pair of tiles that are in the reverse order from where they ought to be. In our case, the bigger number is in front of the smaller one.



![Capture.JPG](attachment:Capture.JPG)

In [3]:
def count_inversion(s):
    count = 0
    for i in range(len(s)):#0-8    
        for j in range(i+1,len(s)):        
            if s[j]!=0 and s[i] > s[j]: count += 1
    return count

In [4]:
s = get_state(4)
print(s)
print(count_inversion(s))

[[13 10  7  9]
 [11  0 14  8]
 [ 1  2  5  4]
 [ 3 12  6 15]]
[13, 10, 7, 9, 11, 0, 14, 8, 1, 2, 5, 4, 3, 12, 6, 15]
59


# **Find blank row**

In [5]:
# find row position of the blank tile
def get_blank_row(s):
    for i in range(len(s)):
        if s[i]==0: return i//4


# Solvability Rules

In [6]:
# apply the rules to decide solvability
#  N, I, R
# define a method to return solvability (input S)
# return True if solvable or False if not

def isSolvable(initialState):
    N = len(initialState)
    I = count_inversion(initialState)
    R = get_blank_row(initialState)
    if N%2==1: 
        if I%2==0: return True
        else: return False
    else: 
        if (I+R)%2==1: return True
        else: return False
  


In [7]:
# use a while loop to generate a solvable initial state
S = get_state(4)
print(isSolvable(S))

[[ 8 14 15 13]
 [ 6  4  5  3]
 [ 0 11  7 10]
 [ 9  2 12  1]]
True
